### ISSUE TITLE
Issue with language of months

### ISSUE THREAD

**Issue by bahrus** [RoXuS/range-datepicker#1]
Looking great so far. 

I'm finding that when I first open the range picker, it usually shows one or both months in my local language (English), but not when I navigate to other months (and back again).  In that case it seems to default to French.

**Comment by RoXuS** [comment]
I am on it @bahrus, I am trying to solve it. It happens when several range-datepicker are included in the same page and at least one have a different locale.

Thx !

**Comment by RoXuS** [comment]
@bahrus fixed with https://github.com/RoXuS/range-datepicker/commit/0be89408fe0aefad2b947dbf47ed00ce8439e10e .

Can you confirm ?

Thx

**Comment by bahrus** [comment]
looks good!
