### ISSUE TITLE
Get error when try to build

### ISSUE THREAD

**Issue by m3alamin** [RoXuS/range-datepicker#10]
When try to build using polymer build --bundle terminal throw error 

 class extends subclass {
range-datepicker-behavior.js(9,16) warning [unknown-superclass] - Unable to resolve superclass subclass

**Comment by RoXuS** [comment]
Hello @m3alamin, it is just a warning no ?
It doesn't found the behavior (see https://github.com/Polymer/polymer-cli/issues/734)

**Comment by m3alamin** [comment]
Hi, @RoXuS Thanks for your replay. Yes, It is just a warning.

**Comment by mh2k9** [comment]
Add annotation _@polymerMixin_ before your subclass. Example:

/* @polymerMixin */
const RangeDatepickerBehavior = subclass =>

**Comment by RoXuS** [comment]
Thx mh2k9 -> a4fd3cfe7e3316618b9bf204c5e2d5576468dd55
