### ISSUE TITLE
Polymer 2 - support?

### ISSUE THREAD

**Issue by ald890** [RoXuS/range-datepicker#18]
Does the component support Polymer 2 or will you plan a transition?

**Comment by RoXuS** [comment]
@ald890 this component is in Polymer 2 so it supports polymer 2.

**Comment by ald890** [comment]
Does it work in Polymer 1?

**Comment by RoXuS** [comment]
I don't test but probably no.

**Comment by ald890** [comment]
Do you know of any other datapicker with date range support that supports Polymer 1.0?

**Comment by RoXuS** [comment]
probably -> http://vaadin.com/elements/vaadin-date-picker

**Comment by ald890** [comment]
Do not support date range :( I can find anything which support date range. I need support for Polymer 1 and 2 in component.
