### ISSUE TITLE
Component missing from webcomponents.org

### ISSUE THREAD

**Issue by bahrus** [RoXuS/range-datepicker#19]
I remember seeing this nice component on webcomponents.org.  It doesn't seem to be there anymore.  Not sure if that was intentional.  I know in my case one of the components I registered got removed.  I attribute it to a glitch.  Anyway, hoping you will put this back.

**Comment by RoXuS** [comment]
Thx, it was deleted, strange !!

It is back !! https://www.webcomponents.org/element/RoXuS/range-datepicker
