### ISSUE TITLE
Date calendars are disappearing for iPad view

### ISSUE THREAD

**Issue by Janie-w3** [RoXuS/range-datepicker#9]
I'm using 

> Basic range-datepicker-input by using your custom inputs (with template)

When I tap to select from calendar then calendars are getting disappeared instead of selecting date/range.

Is there any way to use it for iPad view?

**Comment by RoXuS** [comment]
Thx @Janie-w3, it seems to be a bug from `iron-dropdown` component. I have opened an issue (https://github.com/PolymerElements/iron-dropdown/issues/143).

**Comment by RoXuS** [comment]
It works as expected with the last version of `iron-dropdown`.
